name: ritha_mobile
description: Ritha — your wardrobe assistant.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  go_router: ^14.6.2
  web_socket_channel: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  device_calendar: ^4.3.3
  permission_handler: ^11.3.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
