# Generated by Django 6.0.3 on 2026-03-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_user_email_token_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_calendar_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_calendar_password',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_calendar_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apple_calendar_username',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
