# Generated by Django 6.0.3 on 2026-03-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_user_apple_calendar_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
