# Generated by Django 6.0.3 on 2026-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_user_location_lat_user_location_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_push_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
