# Generated by Django 6.0.3 on 2026-03-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_device_push_token_user_push_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outlook_calendar_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='outlook_calendar_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='outlook_calendar_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
