# Generated by Django 6.0.3 on 2026-03-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_user_outlook_calendar_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
