# Generated by Django 5.2.13 on 2026-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_sub',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
