# Generated by Django 5.2.13 on 2026-07-14 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_add_shared_wardrobe_to_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_range', models.CharField(blank=True, max_length=60)),
                ('role', models.CharField(blank=True, max_length=40)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('why', models.TextField(blank=True)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_shopping_items', to='itinerary.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_shopping_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['purchased', '-created_at'],
                'indexes': [models.Index(fields=['user', 'purchased'], name='itinerary_s_user_id_0fcdcd_idx')],
            },
        ),
    ]
