"""Influencer referral codes — attribution on signup + owner tracking."""

import pytest
from referrals.models import ReferralCode, ReferralSignup

from .factories import UserFactory

pytestmark = pytest.mark.django_db


def register(client, email, referral_code=None):
    body = {"email": email, "password": "testpass99", "first_name": "Sam"}
    if referral_code is not None:
        body["referral_code"] = referral_code
    return client.post("/api/auth/register/", body, content_type="application/json")


def login(client, user):
    r = client.post(
        "/api/auth/login/", {"email": user.email, "password": "testpass99"}, content_type="application/json"
    )
    return r.json()


def hdr(tokens):
    return {"HTTP_AUTHORIZATION": f"Bearer {tokens['access']}"}


class TestCodeModel:
    def test_code_is_normalized_uppercase(self):
        rc = ReferralCode.objects.create(code="  maya20 ", name="Maya")
        assert rc.code == "MAYA20"

    def test_blank_code_is_autogenerated(self):
        rc = ReferralCode.objects.create(code="", name="Auto")
        assert rc.code and rc.code == rc.code.upper()
        assert len(rc.code) >= 8


class TestAttribution:
    def test_signup_with_code_is_attributed(self, client):
        rc = ReferralCode.objects.create(code="MAYA20", name="Maya")
        r = register(client, "new1@ritha.com", "MAYA20")
        assert r.status_code == 201
        assert rc.signups.count() == 1
        assert ReferralSignup.objects.get(code=rc).user.email == "new1@ritha.com"

    def test_code_match_is_case_insensitive(self, client):
        rc = ReferralCode.objects.create(code="MAYA20", name="Maya")
        assert register(client, "new2@ritha.com", "maya20").status_code == 201
        assert rc.signups.count() == 1

    def test_unknown_code_still_registers_without_attribution(self, client):
        r = register(client, "new3@ritha.com", "NOPE123")
        assert r.status_code == 201
        assert ReferralSignup.objects.count() == 0

    def test_inactive_code_is_not_attributed(self, client):
        ReferralCode.objects.create(code="OLD1", name="Retired", is_active=False)
        assert register(client, "new4@ritha.com", "OLD1").status_code == 201
        assert ReferralSignup.objects.count() == 0

    def test_signup_without_code_is_fine(self, client):
        assert register(client, "new5@ritha.com").status_code == 201
        assert ReferralSignup.objects.count() == 0

    def test_counts_track_verified_separately(self, client):
        rc = ReferralCode.objects.create(code="MAYA20", name="Maya")
        register(client, "a@ritha.com", "MAYA20")  # unverified on signup
        register(client, "b@ritha.com", "MAYA20")
        assert rc.signup_count == 2
        assert rc.verified_count == 0


class TestValidateEndpoint:
    def test_valid_code_returns_name(self, client):
        ReferralCode.objects.create(code="MAYA20", name="Maya")
        r = client.get("/api/referrals/validate/?code=maya20")
        assert r.status_code == 200
        assert r.json() == {"valid": True, "code": "MAYA20", "name": "Maya"}

    def test_unknown_code_is_invalid(self, client):
        r = client.get("/api/referrals/validate/?code=NOPE")
        assert r.status_code == 200
        assert r.json() == {"valid": False}


class TestStatsEndpoint:
    def test_requires_admin(self, client):
        assert client.get("/api/referrals/stats/").status_code in (401, 403)
        user = UserFactory()
        assert client.get("/api/referrals/stats/", **hdr(login(client, user))).status_code == 403

    def test_admin_sees_per_code_counts(self, client):
        rc = ReferralCode.objects.create(code="MAYA20", name="Maya")
        register(client, "x@ritha.com", "MAYA20")
        admin = UserFactory(is_staff=True)
        r = client.get("/api/referrals/stats/", **hdr(login(client, admin)))
        assert r.status_code == 200
        body = r.json()
        assert body["total_signups"] == 1
        row = next(row for row in body["results"] if row["code"] == "MAYA20")
        assert row["signups"] == 1 and row["name"] == "Maya"
        assert row["share_path"] == "/?ref=MAYA20"
        _ = rc  # code row present
