# Generated by Django 5.2.13 on 2026-07-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_wardrobe', '0002_add_invitation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedwardrobe',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
