# Generated by Django 6.0.3 on 2026-03-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itinerary', '0001_initial'),
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main Piece'), ('layer', 'Layer'), ('shoes', 'Shoes'), ('bag', 'Bag'), ('other', 'Other')], default='main', max_length=10)),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.clothingitem')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('daily', 'Daily Look'), ('trip', 'Trip Planner'), ('manual', 'Manual')], default='daily', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('weather_snapshot', models.JSONField(blank=True, default=dict)),
                ('accepted', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itinerary.calendarevent')),
                ('items', models.ManyToManyField(through='outfits.OutfitItem', to='wardrobe.clothingitem')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itinerary.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='outfititem',
            name='outfit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfits.outfitrecommendation'),
        ),
        migrations.AlterUniqueTogether(
            name='outfititem',
            unique_together={('outfit', 'clothing_item')},
        ),
    ]
