# Generated by Django 6.0.3 on 2026-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitrecommendation',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
