# Generated by Django 6.0.3 on 2026-03-15 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
        ('outfits', '0002_outfitrecommendation_points_awarded'),
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outfitrecommendation',
            index=models.Index(fields=['user', 'date'], name='outfit_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='outfitrecommendation',
            index=models.Index(fields=['user', 'source'], name='outfit_user_source_idx'),
        ),
    ]
