# Generated by Django 6.0.3 on 2026-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('place_name', models.CharField(blank=True, max_length=200)),
                ('rule_type', models.CharField(choices=[('cover_head', 'Head Covering Required'), ('cover_shoulders', 'Shoulders Must Be Covered'), ('cover_knees', 'Knees Must Be Covered'), ('no_bare_feet', 'No Bare Feet'), ('modest_dress', 'Modest Dress Required'), ('remove_shoes', 'Remove Shoes'), ('festival_wear', 'Festival / Event Specific'), ('color_warning', 'Colour Significance'), ('general', 'General Etiquette')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('required', 'Required')], default='info', max_length=10)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country', 'city'],
            },
        ),
        migrations.CreateModel(
            name='LocalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('clothing_note', models.TextField(blank=True)),
                ('start_month', models.PositiveSmallIntegerField()),
                ('end_month', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
