# Generated by Django 6.0.3 on 2026-03-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultural', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localevent',
            options={'ordering': ['country', 'name']},
        ),
    ]
