// src/pages/ReferralStatsPage.jsx — owner-only influencer referral tracking
import { useEffect, useState, useCallback } from 'react'
import { referrals as referralsApi } from '../api/index.js'

const ORIGIN = typeof window !== 'undefined' ? window.location.origin : ''

function fmtDate(iso) {
  if (!iso) return '—'
  try {
    return new Date(iso).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' })
  } catch {
    return iso
  }
}

export default function ReferralStatsPage() {
  const [rows, setRows]       = useState([])
  const [totals, setTotals]   = useState({ codes: 0, signups: 0 })
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState('')
  const [copied, setCopied]   = useState('')

  const load = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const data = await referralsApi.stats()
      setRows(data?.results || [])
      setTotals({ codes: data?.total_codes || 0, signups: data?.total_signups || 0 })
    } catch (err) {
      if (err.response?.status === 403) {
        setError('This page is for administrators only.')
      } else {
        setError(err.response?.data?.error?.message || err.message || 'Could not load referral stats.')
      }
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => { load() }, [load])

  const copyLink = async (code) => {
    const url = `${ORIGIN}/?ref=${code}`
    try {
      await navigator.clipboard.writeText(url)
      setCopied(code)
      window.__toast?.('Share link copied', 'success')
      setTimeout(() => setCopied((c) => (c === code ? '' : c)), 2000)
    } catch {
      window.__toast?.(url, 'info')
    }
  }

  const th = { textAlign: 'left', padding: '10px 14px', fontSize: '0.72rem', letterSpacing: '0.06em', textTransform: 'uppercase', color: 'var(--cream-dim)', fontWeight: 600, borderBottom: '1px solid var(--border)', whiteSpace: 'nowrap' }
  const td = { padding: '12px 14px', fontSize: '0.9rem', color: 'var(--cream)', borderBottom: '1px solid var(--border)', verticalAlign: 'middle' }

  return (
    <div>
      <div className="page-header fade-up">
        <div className="date-line">Growth</div>
        <h1>Referral Tracking</h1>
        <p>Signups generated by each influencer code. Share <code>{ORIGIN}/?ref=CODE</code> and it&apos;s attributed automatically.</p>
      </div>

      {/* Summary tiles */}
      <div className="fade-up" style={{ display: 'flex', gap: 16, marginBottom: 20, flexWrap: 'wrap' }}>
        {[
          { label: 'Active + total codes', value: totals.codes },
          { label: 'Total signups', value: totals.signups },
        ].map((t) => (
          <div key={t.label} className="card" style={{ flex: '1 1 180px', minWidth: 160 }}>
            <div className="card-label">{t.label}</div>
            <div style={{ fontFamily: 'var(--font-display)', fontSize: '2rem', color: 'var(--cream)', lineHeight: 1.1 }}>
              {t.value}
            </div>
          </div>
        ))}
        <button className="btn btn-ghost btn-sm" onClick={load} style={{ alignSelf: 'center' }} disabled={loading}>
          {loading ? 'Refreshing…' : '↻ Refresh'}
        </button>
      </div>

      {error && (
        <div className="alert alert-error" style={{ marginBottom: 20 }}>⚠ {error}</div>
      )}

      {loading && !rows.length ? (
        <div className="card skeleton fade-up" style={{ height: 160 }} />
      ) : !error && rows.length === 0 ? (
        <div className="card fade-up" style={{ textAlign: 'center', padding: '40px 20px', color: 'var(--cream-dim)' }}>
          <div style={{ fontSize: '2rem', marginBottom: 8 }}>🎁</div>
          No referral codes yet. Create one in the Django admin (<code>Referrals › Referral codes</code>), then share its link.
        </div>
      ) : !error && (
        <div className="card fade-up" style={{ padding: 0, overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 640 }}>
            <thead>
              <tr>
                <th style={th}>Code</th>
                <th style={th}>Influencer</th>
                <th style={{ ...th, textAlign: 'right' }}>Signups</th>
                <th style={{ ...th, textAlign: 'right' }}>Verified</th>
                <th style={th}>Status</th>
                <th style={th}>Created</th>
                <th style={th}>Link</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => (
                <tr key={r.code}>
                  <td style={{ ...td, fontFamily: 'var(--font-mono, monospace)', fontWeight: 600 }}>{r.code}</td>
                  <td style={td}>{r.name}</td>
                  <td style={{ ...td, textAlign: 'right', fontWeight: 700 }}>{r.signups}</td>
                  <td style={{ ...td, textAlign: 'right', color: 'var(--cream-dim)' }}>{r.verified}</td>
                  <td style={td}>
                    <span style={{
                      fontSize: '0.72rem',
                      padding: '3px 8px',
                      borderRadius: 999,
                      border: '1px solid var(--border)',
                      color: r.is_active ? 'var(--sage, #7fa87f)' : 'var(--cream-dim)',
                      background: r.is_active ? 'rgba(127,168,127,.10)' : 'transparent',
                    }}>
                      {r.is_active ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td style={{ ...td, color: 'var(--cream-dim)', whiteSpace: 'nowrap' }}>{fmtDate(r.created_at)}</td>
                  <td style={td}>
                    <button className="btn btn-ghost btn-sm" onClick={() => copyLink(r.code)} title={`${ORIGIN}/?ref=${r.code}`}>
                      {copied === r.code ? '✓ Copied' : '⧉ Copy'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
