# Generated by Django 6.0.3 on 2026-03-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('wear_again', 'Re-wore an item'), ('carry_on_only', 'Switched to carry-on'), ('weight_saved', 'Reduced luggage weight'), ('rental', 'Chose rental over purchase'), ('secondhand', 'Bought secondhand')], max_length=20)),
                ('co2_saved_kg', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('points', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSustainabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('total_co2_saved_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('wear_again_streak', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
