# Generated by Django 6.0.3 on 2026-03-15 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sustainabilitylog',
            index=models.Index(fields=['user', 'action'], name='sustlog_user_action_idx'),
        ),
    ]
