// This file is generated by `flutterfire configure` and overwritten on every
// run. Do not hand-edit values here.
//
// To regenerate after creating the Firebase project:
//
//   1. dart pub global activate flutterfire_cli
//   2. flutterfire configure --project=<your-firebase-project-id>
//
//   The CLI prompts you to select the platforms (android, ios, web), then
//   downloads google-services.json + GoogleService-Info.plist into the
//   correct locations and rewrites this file with the new project's
//   apiKey / appId / projectId values.
//
// Until that's done, importing `DefaultFirebaseOptions.currentPlatform`
// throws so misconfigured builds fail fast rather than silently talking to
// a stale Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw StateError(
      'firebase_options.dart has not been generated for this project. '
      'Run `flutterfire configure --project=<your-firebase-project-id>` '
      'from mobile_flutter/ to regenerate it.',
    );
  }
}
