# Generated by Django 6.0.3 on 2026-03-14 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('activewear', 'Activewear'), ('formal', 'Formal'), ('other', 'Other')], max_length=20)),
                ('formality', models.CharField(choices=[('casual', 'Casual'), ('casual_smart', 'Casual Smart'), ('smart', 'Smart'), ('formal', 'Formal'), ('activewear', 'Activewear')], default='casual', max_length=20)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all', 'All Season')], default='all', max_length=10)),
                ('colors', models.JSONField(default=list)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe/')),
                ('image_clean', models.ImageField(blank=True, null=True, upload_to='wardrobe/clean/')),
                ('tags', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('times_worn', models.PositiveIntegerField(default=0)),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
