# Generated by Django 5.2.13 on 2026-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_regioncluster_clothingitem_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
